#!/usr/bin/env bash
# Regenerate REAL-ARTIFACT-RECEIPTS.md by running the committed tool against
# shipped IPAs.
#
# Receipts are a record of runs against artifacts too large to commit (~220 MB
# each) and too short-lived to link (ios-depot.yml sets retention-days: 14).
# They exist because a claim like "the shipped build verifies clean" is not
# checkable from a diff, and an uncheckable claim is the thing this standard is
# against. They do NOT replace tests/artifact-truth.test.mjs, which is what runs
# in CI and what pins behaviour; a receipt says what happened once, a test says
# what must keep being true.
#
#   ./regenerate.sh <app>=<path-to-App.ipa> [<app>=<path> ...]
#
# e.g. ./regenerate.sh iheartest=/tmp/iht59/App.ipa aware=/tmp/aware/App.ipa
#
# Fetching a shipped IPA from its build run (the redirect target REJECTS the
# Authorization header, so follow it without one):
#   LOC=$(curl -sS -o /dev/null -w '%{redirect_url}' -H "Authorization: Bearer $TOKEN" \
#     "https://api.github.com/repos/<owner>/<repo>/actions/artifacts/<id>/zip")
#   curl -sSL -o artifact.zip "$LOC" && unzip -q artifact.zip
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SKILL="$(dirname "$HERE")"
OUT="$HERE/REAL-ARTIFACT-RECEIPTS.md"
[ $# -gt 0 ] || { echo "usage: $0 <app>=<path-to-App.ipa> [...]" >&2; exit 2; }

{
  echo "# Real-artifact verification receipts"
  echo
  echo "Generated by \`skills/release-verification/receipts/regenerate.sh\`. Do not hand-edit;"
  echo "re-run the script instead. Artifact provenance (which build run each IPA came"
  echo "from) is maintained by hand in SOURCES.md next to this file."
  echo
  echo "WHY THIS EXISTS. The documentation asserts real-artifact results -- \"the shipped"
  echo "build verifies clean\" -- and nothing in a diff substantiates that. A reader can"
  echo "check the synthetic tests, which prove the tool BEHAVES correctly, and then has to"
  echo "take the shipped-build claims on trust. Assertion without checkable evidence is"
  echo "exactly what this standard exists to eliminate, so the runs are recorded here and"
  echo "each artifact is named by sha256 so the claim can be re-checked against the same"
  echo "bytes."
  echo
  echo "WHAT THIS IS NOT. A receipt says what happened once. It does not replace"
  echo "\`tests/artifact-truth.test.mjs\`, which runs in CI and pins what must KEEP being"
  echo "true. IPAs are ~220 MB and expire on ios-depot.yml's retention-days: 14, so they are"
  echo "not committed and cannot be linked; SOURCES.md is how you obtain the same ones."
  echo "Tool commit: $(git -C "$SKILL" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  echo "Captured: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
} > "$OUT"

for arg in "$@"; do
  app="${arg%%=*}"; ipa="${arg#*=}"
  [ -f "$ipa" ] || { echo "no such IPA: $ipa" >&2; exit 2; }
  manifest="$SKILL/schema/$app.release-truth.json"
  [ -f "$manifest" ] || { echo "no manifest for app: $app" >&2; exit 2; }
  {
    echo "## $app"
    echo
    echo "IPA sha256: \`$(sha256_of "$ipa")\`"
    echo
    echo '```'
    echo "\$ node artifact-truth.mjs --ipa <shipped>.ipa --manifest schema/$app.release-truth.json"
    set +e
    node "$SKILL/artifact-truth.mjs" --ipa "$ipa" --manifest "$manifest" 2>&1
    echo "exit=$?"
    set -e

# sha256sum is GNU coreutils and is absent on macOS, which is the platform an
# iOS engineer is most likely to run this on. The old call would abort under
# `set -e` AFTER the output file had already been truncated, leaving a corrupt
# receipt -- a failure that destroys the artifact it was regenerating. Node is
# already a hard dependency of this script (it runs artifact-truth.mjs), so use
# it and drop the platform question entirely.
sha256_of() {
  node -e 'const c=require("node:crypto"),f=require("node:fs");const h=c.createHash("sha256");h.update(f.readFileSync(process.argv[1]));process.stdout.write(h.digest("hex"))' "$1"
}
    echo '```'
    echo
  } >> "$OUT"
done
echo "wrote $OUT"
